<div class="mt-3">
    <form method="POST" class='form-group'>
        <div class='form-floating'><input type="text" name="name" required placeholder="name" class='form-control'><label>Name</label></div>
        <div class='form-floating'><input type="text" name="category" required placeholder="category" class='form-control'><label>Category</label></div>
        <div class='form-floating'><input type="number" name="price" required placeholder="price" class='form-control'><label>Price</label></div>
        <div class='form-floating'><input type="number" name="stock" required placeholder="stock" class='form-control'><label>Stock</label></div>
        <hr>
        <div class='mt-3'>
            <label>MetaData</label>
            <button class='btn btn-light' id="addMeta">+</button>
            <button class='btn btn-light' id="rmMeta">-</button>
        </div>
        <div id="meta" class='mt-3'></div>
        <hr>

        <div class='mt-3 mb-2 row'>
            <div class='col-1'><label>Variations</label></div>
            <div class="col-5"><input id="varList" class='form-control' placeholder="Attributes {Color, Material, Size } (Comma separated values)"></div>
            <div class='col'><button class='btn btn-light' id="addAttr">+</button>
            </div>
        </div>
        <div id="attr" class='mt-3'></div>

        <input type="submit" value="Insert" class='form-control bg-dark text-light'>
    </form>
</div>
<hr>
<div id="search" class='container-fluid'>
    <form class='form-group'><input type='text' class='form-control' value="<?php echo $this->request->getQuery("q"); ?>" placeholder="Search" name="q"><input type="submit" hidden></form><br>
    <table class='table table-striped table-warning'>
        <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Stock</th>
            <th>Price</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        <?php foreach ($data as $v) { ?>
            <tr>
                <td>
                    </span><span><?php echo $v['name'] ?></span>
                <td>
                    <span><?php echo $v['category'] ?>
                </td>
                </td>
                <td>
                    <span><?php echo $v['stock'] ?></span><br>
                </td>
                <td>
                    <span><?php echo $v['price'] ?></span>
                </td>
                <td>
                    <a href=# onclick="showModal('<?php echo $v['_id'] ?>')" class='quickView float-end text-primary fw-bolder text-decoration-none'>View</a>
                </td>
                <td>
                    <a href="/index/remove?id=<?php echo base64_encode($v['_id']) ?>" class='float-end text-danger fw-bolder text-decoration-none'>Remove</a>
                </td>
                <td>
                    <a href="/index/update?id=<?php echo base64_encode($v['_id']) ?>" class='float-end text-success fw-bolder text-decoration-none'>Update</a>
                </td>
            </tr>
</div>
<?php
        } ?>
</table>
</div>