<div class="mt-3">
    <form method="POST" class='form-group'>
        <div>
            <div class='form-floating'><input value="<?php echo $data['name'] ?>" type="text" name="name" placeholder="name" class='form-control'><label>Name</label></div>
            <div class='form-floating'><input value="<?php echo $data['category'] ?>" type="text" name="category" placeholder="email" class='form-control'><label>Category</label></div>
            <div class='form-floating'><input value="<?php echo $data['price'] ?>" type="number" name="price" placeholder="email" class='form-control'><label>Price</label></div>
            <div class='form-floating'><input value="<?php echo $data['stock'] ?>" type="number" name="stock" placeholder="email" class='form-control'><label>Stock</label></div>
        </div>
        <hr>
        <div>
            <p>Metadata</p>
            <button class='btn btn-light' id="addMeta">+</button>
            <button class='btn btn-light' id="rmMeta">-</button>
            <div id="meta" class='mt-3'></div>
            <?php foreach ($meta as $k => $v) { ?>
                <div class='form-floating'><input value="<?php echo $v ?>" type="text" name="meta[<?php echo $k ?>]" placeholder="email" class='form-control'><label><?php echo ucwords($k) ?></label></div>
            <?php } ?>
        </div>
        <hr>
        <p>Variations</p>
        <button class='btn btn-light' id="addAttr">+</button>
        <button class='btn btn-light' id="rmAttr">-</button>
        <div id="attr" class='mt-3'></div>
        <div class='row'>
            <?php foreach ($var as $k => $v) { ?>
                <div class='form-floating col-4'><input value="<?php echo $v['key'] ?>" type="text" name="variations[<?php echo $k ?>][key]" placeholder="email" class='form-control'><label>Key</label></div>
                <div class='form-floating col-4'><input value="<?php echo $v['value'] ?>" type="text" name="variations[<?php echo $k ?>][value]" placeholder="email" class='form-control'><label>Value</label></div>
                <div class='form-floating col-4'><input value="<?php echo $v['price'] ?>" type="number" name="variations[<?php echo $k ?>][price]" placeholder="email" class='form-control'><label>Price</label></div>
            <?php } ?>
        </div>
        <hr>
        <input type="submit" value="Update" class='form-control bg-dark text-light'>
    </form>
</div>