<h2>Place Order</h2>
<div class="mt-3">
    <form method="POST" class='form-group'>
        <div class='form-floating'><input type="text" name="name" required placeholder="name" class='form-control'><label>Name</label></div>
        <p>Products</p>
        <div class='row container'>
            <?php foreach ($productData as $d) { ?>
                <div class='col-4 border p-2 m-1 rounded'>
                    <div>
                        <span class='fs-3'><?php echo $d['name'] ?></span>
                        <span class='text-muted'>/<?php echo $d['category'] ?></span>
                    </div>
                    <div class='row container'>
                        <?php foreach ($d['variations'] as $v) { ?>
                            <div class='col-6 text-warning bg-dark p-1 container'>
                                <label><input name="products[data]" type="radio" value="<?php echo base64_encode(json_encode($v)) ?>">
                                    <div>
                                        <?php foreach ($v as $key => $value) { ?>
                                            <div>
                                                <span><?php echo $key ?>: </span>
                                                <span><?php echo $value ?></span>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </label>
                            </div>
                        <? } ?>
                    </div>
                </div>
            <?php } ?>
            <div class='form-floating'><input type="number" name="products[quantity]" value=1 placeholder="quantity" class='form-control bg-dark text-light'><label>Quantity</label></div>
        </div>
        <hr>
        <input type="submit" value="Place" class='form-control bg-dark text-light'>
    </form>
</div>
<hr>
<div id="search" class='container-fluid'>
    <form class='form-group'><input type='text' class='form-control' value="<?php echo $this->request->getQuery("q"); ?>" placeholder="Today, This week, This Month, Custom [DD-MM-YY:DD-MM-YY]" name="q"><input type="submit" hidden></form><br>
    <table class='table table-striped table-danger table-bordered'>
        <tr>
            <th>Name</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Time</th>
            <th>Status</th>
            <th></th>
        </tr>
        <?php foreach ($orderData as $v) { ?>
            <tr>
                <td>
                    </span><span><?php echo $v['name'] ?></span>
                <td>
                    <span><?php var_dump($v['products']['data']) ?>
                </td>
                </td>
                <td>
                    <span><?php echo $v['products']['quantity'] ?></span><br>
                </td>
                <td>
                    <span><?php echo date("d M, h:m:s",$v['time']) ?></span><br>
                </td>
                <td>
                    <a href="/order/status?id=<?php echo base64_encode($v['_id']) ?>" class='float-end text-dark fw-bolder text-decoration-none'><?php echo $statuses[$v['status']] ?></a>
                </td>
                <td>
                    <a href="/order/remove?id=<?php echo base64_encode($v['_id']) ?>" class='float-end text-danger fw-bolder text-decoration-none'>Remove</a>
                </td>
            </tr>
</div>
<?php
        } ?>
</table>
</div>