<div class="mt-3">
    <form method="POST" class='form-group'>
        <div>
            <div class='form-floating'><input value="<?php echo $data['name'] ?>" type="text" name="name" placeholder="name" class='form-control'><label>Name</label></div>
            <div class='form-floating'><input value="<?php echo $data['category'] ?>" type="text" name="category" placeholder="email" class='form-control'><label>Category</label></div>
            <div class='form-floating'><input value="<?php echo $data['price'] ?>" type="number" name="price" placeholder="email" class='form-control'><label>Price</label></div>
            <div class='form-floating'><input value="<?php echo $data['stock'] ?>" type="number" name="stock" placeholder="email" class='form-control'><label>Stock</label></div>
        </div>
        <hr>
        <div>
            <p>Metadata</p>
            <button class='btn btn-light' id="addMeta">+</button>
            <button class='btn btn-light' id="rmMeta">-</button>
            <div id="meta" class='mt-3'></div>
            <?php foreach ($meta as $k => $v) { ?>
                <div class='form-floating'><input value="<?php echo $v ?>" type="text" name="meta[<?php echo $k ?>]" placeholder="email" class='form-control'><label><?php echo ucwords($k) ?></label></div>
            <?php } ?>
        </div>
        <hr>
        <div>
            <?php foreach ($var as $k => $v) { ?>
                <div class='varItem row rounded mb-2 p-2'>
                    <p class='mb-0'>Variation: <? echo 100+($k+1) ?></p>
                    <?php foreach ($v as $key => $val) {
                    ?>
                        <div class='form-floating col-3'><input value="<?php echo $val ?>" type="text" name="variations[<?php echo 100+($k+1) ?>][<?php echo $key ?>]" placeholder="email" class='form-control'><label><?php echo $key ?></label></div>
                    <?php } ?>
                    <div class='col-2'><button class='btn btn-danger' id="rmAttr">Remove</button></div>
                </div>
                <hr>
            <?php } ?>
        </div>
        <div class='mt-3 mb-2 row'>

            <div class="col-5"><input id="varList" class='form-control' placeholder="Attributes {Color, Material, Size } (Comma separated values)"></div>
            <div class='col'><button class='btn btn-light' id="addAttr">+</button>
            </div>
        </div>
        <div id="attr" class='mt-3'></div>
        <hr>
        <input type="submit" value="Update" class='form-control bg-dark text-light'>
    </form>
</div>