<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <?php
    echo $this->tag->stylesheetLink('https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', true);
    echo $this->tag->stylesheetLink("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css", true);
    ?>
</head>

<body>
    <div class="container">
        <?php require_once APP_PATH."/views/common/header.phtml" ?>
        <?php echo $this->getContent(); ?>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <?php
    echo $this->tag->javascriptInclude("js.js");
    ?>
    
</body>
</html>